#define PPBF_ASCII_33 !
#define PPBF_ASCII_34 "
#define PPBF_ASCII_35 #
#define PPBF_ASCII_36 $
#define PPBF_ASCII_37 %
#define PPBF_ASCII_38 &
#define PPBF_ASCII_40 (
#define PPBF_ASCII_41 )
#define PPBF_ASCII_42 *
#define PPBF_ASCII_43 +
#define PPBF_ASCII_44 ,
#define PPBF_ASCII_45 -
#define PPBF_ASCII_46 .
#define PPBF_ASCII_47 /
#define PPBF_ASCII_48 0
#define PPBF_ASCII_49 1
#define PPBF_ASCII_50 2
#define PPBF_ASCII_51 3
#define PPBF_ASCII_52 4
#define PPBF_ASCII_53 5
#define PPBF_ASCII_54 6
#define PPBF_ASCII_55 7
#define PPBF_ASCII_56 8
#define PPBF_ASCII_57 9
#define PPBF_ASCII_58 :
#define PPBF_ASCII_59 ;
#define PPBF_ASCII_60 <
#define PPBF_ASCII_61 =
#define PPBF_ASCII_62 >
#define PPBF_ASCII_63 ?
#define PPBF_ASCII_64 @
#define PPBF_ASCII_65 A
#define PPBF_ASCII_66 B
#define PPBF_ASCII_67 C
#define PPBF_ASCII_68 D
#define PPBF_ASCII_69 E
#define PPBF_ASCII_70 F
#define PPBF_ASCII_71 G
#define PPBF_ASCII_72 H
#define PPBF_ASCII_73 I
#define PPBF_ASCII_74 J
#define PPBF_ASCII_75 K
#define PPBF_ASCII_76 L
#define PPBF_ASCII_77 M
#define PPBF_ASCII_78 N
#define PPBF_ASCII_79 O
#define PPBF_ASCII_80 P
#define PPBF_ASCII_81 Q
#define PPBF_ASCII_82 R
#define PPBF_ASCII_83 S
#define PPBF_ASCII_84 T
#define PPBF_ASCII_85 U
#define PPBF_ASCII_86 V
#define PPBF_ASCII_87 W
#define PPBF_ASCII_88 X
#define PPBF_ASCII_89 Y
#define PPBF_ASCII_90 Z
#define PPBF_ASCII_91 [
#define PPBF_ASCII_92 \\
//
#define PPBF_ASCII_93 ]
#define PPBF_ASCII_94 ^
#define PPBF_ASCII_95 _
#define PPBF_ASCII_96 `
#define PPBF_ASCII_97 a
#define PPBF_ASCII_98 b
#define PPBF_ASCII_99 c
#define PPBF_ASCII_100 d
#define PPBF_ASCII_101 e
#define PPBF_ASCII_102 f
#define PPBF_ASCII_103 g
#define PPBF_ASCII_104 h
#define PPBF_ASCII_105 i
#define PPBF_ASCII_106 j
#define PPBF_ASCII_107 k
#define PPBF_ASCII_108 l
#define PPBF_ASCII_109 m
#define PPBF_ASCII_110 n
#define PPBF_ASCII_111 o
#define PPBF_ASCII_112 p
#define PPBF_ASCII_113 q
#define PPBF_ASCII_114 r
#define PPBF_ASCII_115 s
#define PPBF_ASCII_116 t
#define PPBF_ASCII_117 u
#define PPBF_ASCII_118 w
#define PPBF_ASCII_119 x
#define PPBF_ASCII_120 y
#define PPBF_ASCII_121 z
#define PPBF_ASCII_123 {
#define PPBF_ASCII_124 |
#define PPBF_ASCII_125 }
#define PPBF_ASCII_126 ~
